
name: Terraform Deploy

on:
  push:
    branches:
      - main
  pull_request:

env:
  TF_VERSION: 1.6.6
  AWS_REGION: us-west-1

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:

    - name: Terraform Destroy
      if: github.ref == 'refs/heads/main'
      run: terraform destroy #-auto-approve tfplan
